version: '3'

services:
  erlang:
    image: erlang:22.1
    volumes:
      - ./:/emqx_auth_mongo
    networks:
      - emqx_bridge
    depends_on:
      - mongo_server
    tty: true

  mongo_server:
    image: mongo:${MONGO_TAG}
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mqtt
    networks:
      - emqx_bridge
    command:
      --ipv6
      --bind_ip_all

networks:
  emqx_bridge:
    driver: bridge
