name: 'Detect profiles'
outputs:
  profiles:
    description: 'Detected profiles'
    value: ${{ steps.detect-profiles.outputs.profiles}}

runs:
  using: composite
  steps:
    - id: detect-profiles
      shell: bash
      run: |
        if make emqx-ee --dry-run > /dev/null 2>&1; then
          echo "profiles=[\"emqx-ee\"]" >> $GITHUB_OUTPUT
          echo "EMQX_NAME=emqx-ee" >> $GITHUB_ENV
        else
          echo "profiles=[\"emqx\", \"emqx-edge\"]" >> $GITHUB_OUTPUT
          echo "EMQX_NAME=emqx" >> $GITHUB_ENV
        fi
