apiVersion: v1
kind: Service
metadata:
  name: {{ include "emqx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | default "Cluster" }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs: {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
  {{- if not (empty .Values.service.mqtt) }}
  - name: mqtt
    port: {{ .Values.service.mqtt }}
    protocol: TCP
    targetPort: mqtt
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.mqtt)) }}
    nodePort: {{ .Values.service.nodePorts.mqtt }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  {{- end }}
  {{- if not (empty .Values.service.mqttssl) }}
  - name: mqttssl
    port: {{ .Values.service.mqttssl }}
    protocol: TCP
    targetPort: mqttssl
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.mqttssl)) }}
    nodePort: {{ .Values.service.nodePorts.mqttssl }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  {{- end }}
  {{- if not (empty .Values.service.ws) }}
  - name: ws
    port: {{ .Values.service.ws }}
    protocol: TCP
    targetPort: ws
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.ws)) }}
    nodePort: {{ .Values.service.nodePorts.ws }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  {{- end }}
  {{- if not (empty .Values.service.wss) }}
  - name: wss
    port: {{ .Values.service.wss | default 8084 }}
    protocol: TCP
    targetPort: wss
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.wss)) }}
    nodePort: {{ .Values.service.nodePorts.wss }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  {{- end }}
  {{- if not (empty .Values.service.dashboard) }}
  - name: dashboard
    port: {{ .Values.service.dashboard  }}
    protocol: TCP
    targetPort: dashboard
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.dashboard)) }}
    nodePort: {{ .Values.service.nodePorts.dashboard }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "emqx.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: {{ .Values.service.clusterIP | default "None" }}
  publishNotReadyAddresses: true
  ports:
  - name: ekka
    port: 4370
    protocol: TCP
    targetPort: ekka
  selector:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
