version: '3'

services:
  erlang:
    container_name: erlang
    image: emqx/build-env:erl23.2.7-ubuntu20.04
    volumes:
      - ../../:/emqx
    working_dir: /emqx
    networks:
      - emqx_bridge
    depends_on:
      - mysql_server
    tty: true


  mysql_server:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:${MYSQL_TAG}
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: public
      MYSQL_DATABASE: mqtt
      MYSQL_USER: emqx
    ports:
      - "${MAP_PORT}:3306"
    volumes:
      - ../../apps/emqx_auth_mysql/test/emqx_auth_mysql_SUITE_data/init-db.txt:/etc/mysql-init-db.txt
    networks:
      - emqx_bridge
    command:
      --bind-address "::"
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --init-file=/etc/mysql-init-db.txt
    healthcheck:
      test: " mysql -uemqx -ppublic -e 'use mqtt;'"
      interval: 5s
      timeout: 5s
      retries: 20


networks:
  emqx_bridge:
    driver: bridge
    name: emqx_bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.100.100.0/24
          gateway: 172.100.100.1
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
