version: '3'

services:
  erlang:
    image: erlang:22.1
    volumes:
      - ../:/emqx_auth_redis    
    networks:
      - emqx_bridge
    depends_on:
      - redis_server
    tty: true

  redis_server:
    build:
        context: ./emqx-redis
        args:
            BUILD_FROM: redis:${REDIS_TAG}
    image: emqx-redis
    restart: always
    networks:
      - emqx_bridge

networks:
  emqx_bridge:
    driver: bridge
