name: 'Create MacOS package'
inputs:
  otp: # 24.2.1-1, 23.3.4.9-3
    required: true
    type: string
  os:
    required: false
    type: string
    default: macos-11
  apple_id_password:
    required: true
    type: string
  apple_developer_identity:
    required: true
    type: string
  apple_developer_id_bundle:
    required: true
    type: string
  apple_developer_id_bundle_password:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: prepare
      shell: bash
      run: |
        brew update
        brew install curl zip unzip gnu-sed coreutils unixodbc freetds openssl@1.1
        echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
        echo "/usr/local/bin" >> $GITHUB_PATH
    - uses: actions/cache@v3
      id: cache
      with:
        path: /opt/erlang/${{ inputs.otp }}
        key: otp-install-${{ inputs.otp }}-${{ inputs.os }}-static-ssl-disable-hipe-disable-jit
    - name: build erlang
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        git clone --depth 1 --branch OTP-${{ inputs.otp }} https://github.com/emqx/otp.git $HOME/otp-${{ inputs.otp }}
        cd $HOME/otp-${{ inputs.otp }}
        ./configure --disable-dynamic-ssl-lib --with-ssl=/usr/local/opt/openssl@1.1 --disable-hipe --disable-jit --prefix=/opt/erlang/${{ inputs.otp }}
        make -j$(nproc)
        sudo make install
    - name: build
      env:
        AUTO_INSTALL_BUILD_DEPS: 1
        APPLE_SIGN_BINARIES: 1
        APPLE_ID: developers@emqx.io
        APPLE_TEAM_ID: 26N6HYJLZA
        APPLE_ID_PASSWORD: ${{ inputs.apple_id_password }}
        APPLE_DEVELOPER_IDENTITY: ${{ inputs.apple_developer_identity }}
        APPLE_DEVELOPER_ID_BUNDLE: ${{ inputs.apple_developer_id_bundle }}
        APPLE_DEVELOPER_ID_BUNDLE_PASSWORD: ${{ inputs.apple_developer_id_bundle_password }}
      shell: bash
      run: |
        export PATH="/opt/erlang/${{ inputs.otp }}/bin:$PATH"
        make ensure-rebar3
        sudo cp rebar3 /usr/local/bin/rebar3
        make ${EMQX_NAME}-zip
    - name: test
      shell: bash
      run: |
        pkg_name=$(basename _packages/${EMQX_NAME}/${EMQX_NAME}-*.zip)
        unzip -q _packages/${EMQX_NAME}/$pkg_name
        # test with a spaces in path
        mv ./emqx "./emqx  home/"
        cd "./emqx  home/"
        gsed -i '/emqx_telemetry/d' data/loaded_plugins
        ./bin/emqx start || cat log/erlang.log.1
        ready='no'
        for i in {1..10}; do
          if curl -fs 127.0.0.1:18083 > /dev/null; then
            ready='yes'
            break
          fi
          sleep 1
        done
        if [ "$ready" != "yes" ]; then
          echo "Timed out waiting for emqx to be ready"
          cat log/erlang.log.1
          exit 1
        fi
        ./bin/emqx_ctl status
        if ! ./bin/emqx stop; then
          cat log/erlang.log.1 || true
          cat log/emqx.log.1 || true
          echo "failed to stop emqx"
          exit 1
        fi
        cd ..
        # test with a spaces in path
        rm -rf "emqx  home"
