version: '3.9'

services:
  ldap_server:
    container_name: ldap
    build:
      context: ../..
      dockerfile: .ci/docker-compose-file/openldap/Dockerfile
      args: 
        LDAP_TAG: ${LDAP_TAG}
    image: openldap 
    ports:
      - 389:389
    restart: always
    networks:
      emqx_bridge:
        ipv4_address: 172.100.239.10
        ipv6_address: 2001:3200:3200::10
