version: '3.9'

services:
  redis_server:
    container_name: redis 
    image: redis:${REDIS_TAG}
    command:
        - redis-server
        - "--bind 0.0.0.0 ::"
    restart: always
    networks:
      - emqx_bridge
