version: '3.9'

services:
  mysql_server:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:${MYSQL_TAG}
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: public
      MYSQL_DATABASE: mqtt
      MYSQL_USER: emqx
      MYSQL_PASSWORD: public
    ports:
      - "${MAP_PORT}:3306"
    volumes:
      - ../../apps/emqx_auth_mysql/test/emqx_auth_mysql_SUITE_data/init-db.txt:/etc/mysql-init-db.txt
      - ../../apps/emqx_auth_mysql/test/emqx_auth_mysql_SUITE_data/ca.pem:/etc/certs/ca-cert.pem
      - ../../apps/emqx_auth_mysql/test/emqx_auth_mysql_SUITE_data/server-cert.pem:/etc/certs/server-cert.pem
      - ../../apps/emqx_auth_mysql/test/emqx_auth_mysql_SUITE_data/server-key.pem:/etc/certs/server-key.pem
    networks:
      - emqx_bridge
    command:
      --bind-address "::"
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --init-file=/etc/mysql-init-db.txt
      --ssl-ca=/etc/certs/ca-cert.pem
      --ssl-cert=/etc/certs/server-cert.pem
      --ssl-key=/etc/certs/server-key.pem
    healthcheck:
      test: " mysql -uemqx -ppublic -e 'use mqtt;'"
      interval: 5s
      timeout: 5s
      retries: 20


#  mysql_client:
#    container_name: mysql_client
#    image: mysql:${MYSQL_TAG}
#    networks:
#      - emqx_bridge
#    depends_on:
#      - mysql_server
#    command:
#      - /bin/bash
#      - -c
#      - |
#        service mysql start
#        echo "show tables;" | mysql -h mysql_server -u root -ppublic mqtt mqtt
#        while [[ $$? -ne 0 ]];do echo "show tables;" | mysql -h mysql_server -u root -ppublic mqtt; done
#        echo "ALTER USER 'emqx'@'%' REQUIRE X509;" | mysql -h mysql_server -u root -ppublic mqtt
