version: '3.9'

services:
  redis_cluster:
    image: redis:${REDIS_TAG}
    container_name: redis
    volumes:
      - ./redis/:/data/conf
    command: bash -c "/bin/bash /data/conf/redis.sh --node cluster && while true; do echo 1; sleep 1; done"
    networks:
      emqx_bridge:
        # Assign a public address. Erlang container cannot find cluster nodes by network-scoped alias (redis_cluster).
        ipv4_address: 172.100.239.14
        ipv6_address: 2001:3200:3200::14
