version: '3.9'

services:
  mysql_server:
    container_name: mysql
    image: mysql:${MYSQL_TAG}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: public
      MYSQL_DATABASE: mqtt
    networks:
      emqx_bridge:
        ipv4_address: 172.100.239.12
        ipv6_address: 2001:3200:3200::12
    command:
      --bind-address "::"
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --skip-symbolic-links
