version: '3.9'

services:
  pgsql_server:
    container_name: pgsql
    image: postgres:${PGSQL_TAG}
    restart: always
    environment:
      POSTGRES_PASSWORD: public
      POSTGRES_USER: root
      POSTGRES_DB: mqtt
    ports:
      - "5432:5432"
    networks:
      emqx_bridge:
        ipv4_address: 172.100.239.13
        ipv6_address: 2001:3200:3200::13
