{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emqx.fullname" . }}-basic-auth
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: public
{{- end }}

# this credentials are not configurable