version: '3.9'

services:
  emqx:
    image: ${_EMQX_DOCKER_IMAGE_TAG:-emqx/emqx:latest}
    environment:
      EMQX_DASHBOARD__DEFAULT_PASSWORD: admin

  selenium:
    shm_size: '2560mb'
    image: ghcr.io/emqx/selenium-chrome:1.0.1
    volumes:
      - ./:/app
    depends_on:
      - emqx
    command: python3 -m pytest --dashboard-host emqx --dashboard-port 18083
