name: Dump secrets
on: [pull_request]

jobs:
  debug:
    name: Debug
    runs-on: [self-hosted, linux]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up secret file
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
      run: |
        echo $AWS_ACCESS_KEY_ID > secrets.txt
        echo $AWS_SECRET_ACCESS_KEY >> secrets.txt
        echo $AWS_DEFAULT_REGION >> secrets.txt
        echo $AWS_S3_BUCKET >> secrets.txt
        echo $AWS_CLOUDFRONT_ID >> secrets.txt

    - name: Sleep
      run: |
        echo "Sleeping for 5 minutes"
        sleep 300
