name: Check Apps Version

on: [pull_request]

jobs:
  check_apps_version:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check apps version
        run: ./scripts/apps-version-check.sh $GITHUB_BASE_REF
