name: Build packages test workflow

concurrency:
  group: build-packages-test-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

permissions:
  contents: read

jobs:
  linux:
    runs-on: [self-hosted, ephemeral, linux, "${{ matrix.arch == 'arm64' && 'arm64' || 'x64' }}"]

    strategy:
      fail-fast: false
      matrix:
        profile:
          - emqx
        os:
          - ubuntu18.04
          - debian11
          - debian10
          - el7
          - amzn2
        arch:
          - amd64
          - arm64
        with_elixir:
          - 'no'
          - 'yes'
        otp:
          - '25.3.2-2'
        builder:
          - '5.3-2'
        elixir:
          - '1.15.7'

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        ref: ${{ github.event.inputs.ref }}
        fetch-depth: 0
    - name: build emqx packages
      env:
        PROFILE: ${{ matrix.profile }}
        ARCH: ${{ matrix.arch }}
        OS: ${{ matrix.os }}
        IS_ELIXIR: ${{ matrix.with_elixir }}
        BUILDER: "ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"
        BUILDER_SYSTEM: force_docker
      run: |
        ./scripts/buildx.sh \
          --profile $PROFILE \
          --arch $ARCH \
          --builder $BUILDER \
          --elixir $IS_ELIXIR \
          --pkgtype pkg
    - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: ${{ matrix.profile }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.with_elixir == 'yes' && '-elixir' && '' }}-${{ matrix.builder }}-${{ matrix.otp }}-${{ matrix.elixir }}.tar.gz
        path: _packages/${{ matrix.profile }}/
        retention-days: 7
