name: Build packages test workflow

concurrency:
  group: build-packages-test-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

permissions:
  contents: read

jobs:
  linux:
    runs-on: [self-hosted, ephemeral, linux, "${{ matrix.arch }}"]
    # always run in builder container because the host might have the wrong OTP version etc.
    # otherwise buildx.sh does not run docker if arch and os matches the target arch and os.
    container:
      image: "docker.io/dyachkov/emqx-builder:5.3-3-1.15.7-25.3.2-${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        profile:
          - emqx
        arch:
          - arm64
        os:
          - el7
        with_elixir:
          - 'no'

    defaults:
      run:
        shell: bash

    steps:
    - name: use pre-built node binary on older platforms
      if: matrix.os == 'el7'
      run: |
        set -eu
        /usr/local/bin/node --version
        rm /__e/node20/bin/node
        ln -s /usr/local/bin/node /__e/node20/bin/node
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        ref: ${{ github.event.inputs.ref }}
        fetch-depth: 0

    - name: fix workdir
      run: |
        set -eu
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        # Align path for CMake caches
        if [ ! "$PWD" = "/emqx" ]; then
          ln -s $PWD /emqx
          cd /emqx
        fi
        echo "pwd is $PWD"

    - name: build emqx packages
      env:
        PROFILE: ${{ matrix.profile }}
        IS_ELIXIR: ${{ matrix.with_elixir }}
        ACLOCAL_PATH: "/usr/share/aclocal:/usr/local/share/aclocal"
      run: |
        set -eu
        if [ "${IS_ELIXIR:-}" == 'yes' ]; then
          make "${PROFILE}-elixir-tgz"
        else
          make "${PROFILE}-tgz"
          make "${PROFILE}-pkg"
        fi
    - name: test emqx packages
      env:
        PROFILE: ${{ matrix.profile }}
        IS_ELIXIR: ${{ matrix.with_elixir }}
      run: |
        set -eu
        if [ "${IS_ELIXIR:-}" == 'yes' ]; then
          ./scripts/pkg-tests.sh "${PROFILE}-elixir-tgz"
        else
          ./scripts/pkg-tests.sh "${PROFILE}-tgz"
          ./scripts/pkg-tests.sh "${PROFILE}-pkg"
        fi
    - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: ${{ matrix.profile }}-${{ matrix.os }}-${{ matrix.arch }}
        path: _packages/${{ matrix.profile }}/
        retention-days: 7
