name: Build packages test workflow

concurrency:
  group: build-packages-test-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

permissions:
  contents: read

jobs:
  linux:
    runs-on: [self-hosted, ephemeral, linux, "${{ matrix.arch }}"]

    strategy:
      fail-fast: false
      matrix:
        profile:
          - emqx
        arch:
          - amd64
          - arm64
        os:
          - el7
        with_elixir:
          - 'yes'
          - 'no'

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        ref: ${{ github.event.inputs.ref }}
        fetch-depth: 0
    - name: build emqx packages
      run: |
        ./scripts/buildx.sh \
          --profile ${{ matrix.profile }} \
          --pkgtype pkg \
          --builder ghcr.io/emqx/emqx-builder/5.3-2:1.15.7-26.2.1-2-${{ matrix.os }} \
          --elixir ${{ matrix.with_elixir }}
    - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: ${{ matrix.profile }}-${{ matrix.os }}-${{ matrix.arch }}
        path: _packages/${{ matrix.profile }}/
        retention-days: 7
