name: Check Rebar Dependencies

on: [pull_request]

jobs:
  check_deps_integrity:
    runs-on: ubuntu-20.04
    container: ghcr.io/emqx/emqx-builder/4.4-19:24.1.5-3-ubuntu20.04

    steps:
      - uses: actions/checkout@v2
      - name: Run check-deps-integrity.escript
        run: ./scripts/check-deps-integrity.escript
