name: Elvis Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "$GITHUB_BASE_REF"
          echo "$GITHUB_HEAD_REF"
           ./elvis-check.sh $GITHUB_BASE_REF $GITHUB_HEAD_REF
