name: Run static checks

concurrency:
  group: static-check-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron:  '0 */6 * * *'
  push:
    tags:
      - v*
      - e*
  workflow_dispatch:

jobs:
  run_static_analysis:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: "master"
            container: "ghcr.io/emqx/emqx-builder/5.0-3:24.1.5-3-alpine3.14"
          - branch: "main-v4.4"
            container: "ghcr.io/emqx/emqx-builder/4.4-4:24.1.5-3-ubuntu20.04"
          - branch: "main-v4.3"
            container: "emqx/build-env:erl23.2.7.2-emqx-3-ubuntu20.04"

    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    - name: xref
      run: make xref
    - name: dialyzer
      run: make dialyzer
