name: Run Configuration tests

concurrency:
  group: conftest-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      builder:
        required: true
        type: string

permissions:
  contents: read

jobs:
  run_conf_tests:
    runs-on: ${{ endsWith(github.repository, '/emqx') && 'ubuntu-22.04' || fromJSON('["self-hosted","ephemeral","linux","x64"]') }}
    container: ${{ inputs.builder }}
    strategy:
      fail-fast: false
      matrix:
        profile:
          - emqx
          - emqx-enterprise
    steps:
      - uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: ${{ matrix.profile }}
      - name: extract artifact
        run: |
          unzip -o -q ${{ matrix.profile }}.zip
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: cat .env | tee -a $GITHUB_ENV
      - run: make ${{ matrix.profile }}
      - run: ./scripts/test/check-example-configs.sh
      - run: ./scripts/conf-test/run.sh
      - name: print erlang log
        if: failure()
        run: |
          cat _build/${{ matrix.profile }}/rel/emqx/logs/erlang.log.*
      - uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        if: failure()
        with:
          name: conftest-logs-${{ matrix.profile }}
          path: _build/${{ matrix.profile }}/rel/emqx/logs
          retention-days: 7
